" coding system
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set ambiwidth=double

" general settings
set nocompatible
set backspace=indent,eol,start
set list
set autochdir

set autoindent
set shiftwidth=4
set tabstop=4
set smarttab
set expandtab

set lbr
set formatoptions+=mM

set sm
set number
set mouse=a

set history=128
set nobackup
set nowritebackup
set backupdir=/tmp
set directory=/tmp

" plugin
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

syntax enable
filetype plugin indent on

if (has('gui_running'))
    set background=light
else
    set background=dark
endif

colorscheme solarized

" For Python
let g:pydiction_location='~/.vim/bundle/Pydiction/complete-dict'

set listchars=tab:>-,trail:.,extends:>,eol:$
autocmd BufRead *.py set smartindent expandtab
autocmd BufWritePre *.py :%s/\s\+$//e

" For Javascript
autocmd BufRead *.js set smartindent expandtab!

" For Windows
if (has('gui_win32'))
    au GUIEnter * simalt ~x
    set guifont=Consolas:h13:cANSI
endif
