install: add-repositories
	echo "starting to install..."

add-repositories:
	add-apt-repository ppa:uwsgi/release
	add-apt-repository ppa:nginx/stable
	wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
