#!/bin/bash

if [ -f ~/.rvm/scripts/rvm ]; then
	source ~/.rvm/scripts/rvm
fi

platform=`uname`

if [ $platform == 'Darwin' ]; then
    alias ls='ls -G'
elif [ $platform == 'Linux' ]; then
    alias ls='ls --color=auto'
fi

alias ll='ls -lsh'
alias la='ls -a'

alias du='du -h'
alias df='df -h'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
